version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./docker/resources/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network-name

  proxy:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - ./docker/resources/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network-name

  php-fpm:
    image: php:7.3-fpm
    volumes:
      - .:/app
      - ./docker/resources/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - my-network-name

networks:
  my-network-name: